### ISSUE TITLE
Installation via pods fails

### ISSUE THREAD

**Issue by mrzaheerabbas** [CleverPumpkin/CrispyCalendar#2]
Whenever I try to install it via CocoaPod it gives error below:

<img width="774" alt="Screen Shot 2019-04-29 at 2 40 28 PM" src="https://user-images.githubusercontent.com/39299902/56888164-cd123900-6a8c-11e9-8535-0199bf5c0da7.png">

**Comment by r-garifullin** [comment]
@mrzaheerabbas this this already fixed, I can try it now!
